name: Update README

on:
  push:
    branches: [master]
  # Disabled for PRs to avoid conflicts with manual README
  # pull_request:
  #   branches: [master]

jobs:
  goreadme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
        
    - name: Update readme according to Go doc
      uses: posener/goreadme@v1
      with:
        badge-travisci: 'false'
        badge-codecov: 'true'
        badge-godoc: 'true'
        badge-goreadme: 'true'
        recursive: 'true'
        # Optional: Token allows goreadme to comment the PR with diff preview.
        github-token: '${{ secrets.GITHUB_TOKEN }}'